//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1525585_CO5027_MuslimLifestyle
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int ProdID { get; set; }
        public string ProdName { get; set; }
        public decimal ProdPrice { get; set; }
        public int ProdQty { get; set; }
        public string ProdStatus { get; set; }
        public string ImgAlt { get; set; }
        public Nullable<int> ImgWidth { get; set; }
        public Nullable<int> ImgHeight { get; set; }
        public string ImgExt { get; set; }
    }
}
